name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: latam-ml-challenge

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t southamerica-east1-docker.pkg.dev/latam-ml-challenge/ml-engineer/latam-api .
          docker push southamerica-east1-docker.pkg.dev/latam-ml-challenge/ml-engineer/latam-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy latam-api \
            --image southamerica-east1-docker.pkg.dev/latam-ml-challenge/ml-engineer/latam-api \
            --platform managed \
            --region southamerica-east1 \
            --allow-unauthenticated
